services:
  graphql:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app  # Mounts your local directory into the container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"